# Netlify configuration for The Riddle Room
[build]
  # Build command - build both static pages and React app
  command = "cp *.html public/ 2>/dev/null || true; cd frontend && npm install && npm run build && cp -r build/* ../public/"
  
  # Directory to publish
  publish = "public"
  
  # Base directory (root)
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # React environment
  REACT_APP_API_URL = "https://your-backend-url.com"
  REACT_APP_SITE_NAME = "The Riddle Room"

# Redirects for The Riddle Room
[[redirects]]
  from = "/"
  to = "/beta.html"
  status = 302

[[redirects]]
  from = "/beta"
  to = "/beta.html"
  status = 200

[[redirects]]
  from = "/beta/success"
  to = "/success.html"
  status = 200

# SPA routing for React app
[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

# Fallback
[[redirects]]
  from = "/*"
  to = "/beta.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
