# Netlify configuration for The Riddle Room - Static Site Only
[build]
  # Build command - will run our custom script
  command = "npm run build"
  
  # Directory to publish
  publish = "public"
  
  # Base directory (root)
  base = "."

[build.environment]
  # Node.js environment (no Python)
  NODE_VERSION = "18"

# Redirects for The Riddle Room
[[redirects]]
  from = "/"
  to = "/beta.html"
  status = 302

[[redirects]]
  from = "/beta"
  to = "/beta.html"
  status = 200

[[redirects]]
  from = "/beta/success"
  to = "/success.html"
  status = 200

# SPA routing for React app
[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

# Fallback
[[redirects]]
  from = "/*"
  to = "/beta.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
