#!/bin/bash
# SendGrid Setup Guide for Cryptic Messages

echo "🔧 SendGrid Setup Guide"
echo "======================="
echo ""
echo "Step 1: Sign up for SendGrid (Free Tier: 100 emails/day)"
echo "Visit: https://signup.sendgrid.com/"
echo ""
echo "Step 2: Verify your email and log in"
echo "Visit: https://app.sendgrid.com/"
echo ""
echo "Step 3: Create an API Key"
echo "1. Go to Settings > API Keys"
echo "2. Click 'Create API Key'"
echo "3. Choose 'Restricted Access'"
echo "4. Give it permissions for 'Mail Send'"
echo "5. Copy the API key (starts with 'SG.')"
echo ""
echo "Step 4: Update your .env file"
echo "Replace 'your-sendgrid-api-key-here' with your actual API key"
echo ""
echo "Step 5: Verify sender identity"
echo "1. Go to Settings > Sender Authentication"
echo "2. Add your email: crypticmessageswithallmighty1@gmail.com"
echo "3. Verify the email address"
echo ""
echo "Step 6: Test the system"
echo "Run: python3 beta_email_manager.py welcome"
echo ""
echo "🎯 SendGrid Benefits:"
echo "- 99% delivery rate"
echo "- No Gmail app password needed"
echo "- Professional email reputation"
echo "- Detailed analytics"
echo "- Free tier: 100 emails/day (perfect for beta)"
echo ""
