#!/bin/bash
# SendGrid Single Sender Setup for Cryptic Messages
# NO DNS RECORDS NEEDED!

echo "🚨 IMPORTANT: You CANNOT add DNS records to ngrok domains!"
echo "============================================================"
echo ""
echo "❌ Problem: corruptedly-trijugate-shiela.ngrok-free.dev is controlled by ngrok"
echo "✅ Solution: Use SendGrid Single Sender Verification instead"
echo ""
echo "📧 SendGrid Single Sender Setup (5 minutes):"
echo "============================================"
echo ""
echo "Step 1: Go to SendGrid Dashboard"
echo "https://app.sendgrid.com/settings/sender_auth"
echo ""
echo "Step 2: Click 'Verify a Single Sender'"
echo ""
echo "Step 3: Fill out the form:"
echo "From Name: The Riddle Room - Cipher Academy"
echo "From Email: crypticmessageswithallmighty1@gmail.com"
echo "Reply To: crypticmessageswithallmighty1@gmail.com"
echo "Company: Cipher Academy"
echo "Address: Your address"
echo "City/State/Zip: Your location"
echo ""
echo "Step 4: Check Gmail for verification email"
echo "Click the verification link"
echo ""
echo "Step 5: Get your SendGrid API Key"
echo "Go to: https://app.sendgrid.com/settings/api_keys"
echo "Create a new key with 'Mail Send' permission"
echo ""
echo "Step 6: Update your .env file"
echo "SENDGRID_API_KEY=SG.your-actual-api-key"
echo ""
echo "Step 7: Test your cryptic message emails"
echo "python3 beta_email_manager.py welcome"
echo ""
echo "🎯 Benefits of Single Sender:"
echo "✅ No DNS setup required"
echo "✅ Works immediately after verification"
echo "✅ Perfect for beta testing"
echo "✅ 99% email delivery rate"
echo "✅ Professional sender reputation"
echo ""
echo "🚀 Your beta users are waiting for Sunday's first challenge!"
echo "Get this setup done so you can send cryptic puzzles to:"
echo "• tkriebe13@gmail.com"
echo "• trash2trophies@gmail.com" 
echo "• test@example.com"
echo ""
echo "🔐 Sunday Challenge: Caesar Cipher - 'WKLV LV MXVW WKH EHJLQQLQJ'"
